version: '3.8'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=${tenant_external_ip}
      - SERVERPORT=51820
      - PEERS=250
      - PEERDNS=${tenant_dns}
      - INTERNAL_SUBNET=${wg_default_addres}
      - ALLOWEDIPS=${tenant_network},${wg_default_network}
      - PERSISTENTKEEPALIVE_PEERS=25
    volumes:
      - /etc/wireguard:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wg-dashboard
    depends_on:
      - wireguard
    environment:
      - WG_CONFIG_DIR=/etc/wireguard
      - FLASK_SECRET_KEY=${flask_secret_key}
      - FLASK_LOGIN_PASSWORD=${flask_login_password}
    volumes:
      - /etc/wireguard:/etc/wireguard:rw
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - wg-network

networks:
  wg-network:
    driver: bridge
